sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
    artifacts:
      - target/metrics.json
excludes:
  # Since this project is built with Java 17, we tweaked the build-next to run with Java 21.
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build-next-java.yml'"
build:
  workflows:
    - name: "ci-build.yml"
      stepCustomizations:
        - action: INSERT_AFTER
          stepId: build-pk-verify
          content:
            name: Run summarizer mojo
            id: maven-run-summarizer
            run: |
              mvn --batch-mode install -DskipTests
              mvn --batch-mode com.exasol:quality-summarizer-maven-plugin:summarize

    - name: "release.yml"
      stepCustomizations:
        - action: INSERT_AFTER
          stepId: build
          content:
            name: Run summarizer mojo
            id: maven-run-summarizer
            run: |
              mvn --batch-mode install -DskipTests
              mvn --batch-mode com.exasol:quality-summarizer-maven-plugin:summarize
