# This file is only used for release guide.
# Actual error codes are based on files error_code_config.yml in individual subfolders.

error-tags:
  QSMP:
    packages:
      - com.exasol.qualitysummarizer
    highest-index: 1
